# Generated by Django 3.1.3 on 2020-11-24 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='date_of_birt',
            new_name='date_of_birth',
        ),
    ]
